language: cpp
compiler: clang++-3.6
# env:
  # - CXX=clang++-3.6
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
install:
script:
  - CXX=clang++-3.6 make -j  # travis overwrites my env settings
  - make test
cache:
  directories:
    - vendor/TestU01-1.2.3/dist
